# Generated by Django 5.0.6 on 2024-07-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_autor_alter_post_texto_alter_post_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(blank=True, default='Teste', max_length=200, null=True),
        ),
    ]
