# Generated by Django 5.0.6 on 2024-07-06 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_titulo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='autor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(default='jdhadj', max_length=200),
            preserve_default=False,
        ),
    ]
