# Generated by Django 5.0.6 on 2024-07-19 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_autor_alter_post_texto_alter_post_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vestibular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('ano', models.DateField()),
                ('resposta', models.TextField()),
                ('vestibular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.vestibular')),
            ],
        ),
    ]
