# Generated by Django 5.0.6 on 2024-07-19 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_questao_ano'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='questao',
            name='vestibular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.tema'),
        ),
    ]
