# Generated by Django 5.0.6 on 2024-07-20 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_tema_alter_questao_vestibular'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='tema',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.tema'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questao',
            name='vestibular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.vestibular'),
        ),
    ]
