# Generated by Django 5.0.6 on 2024-07-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_questao_tema_alter_questao_vestibular'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='img/questao/'),
        ),
    ]
