# Generated by Django 5.0.6 on 2024-07-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_questao_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='conteudo',
        ),
        migrations.AddField(
            model_name='questao',
            name='alternativas',
            field=models.TextField(default='excluir'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questao',
            name='enunciado',
            field=models.TextField(default='excluir'),
            preserve_default=False,
        ),
    ]
